Practica3
juanjosuem/capacitaciones-react pull request #5
Opened 2018-06-04 16:21 UTC by antezananoemi

cambios para la practica 3

2018-06-05 18:15 UTC, juanjosuem requested changes
porfa revisa estos puntos

2018-06-05 18:15 UTC, juanjosuem commented on src/components/practica1/Navigation.js
> +		}
Puedes sacar esta funcion fuera de la clase? no es optimo colocarlo asi, por que cada vez que se haga render se va ejecutar esta funcion

2018-06-05 18:15 UTC, juanjosuem commented on src/components/practica1/Navigation.js
> +			<NavDropdown eventKey={3} title={item.text} id="basic-nav-dropdown">
siempre que iteres y retornes componentes ponle un key al componente si no te dara error

2018-06-05 18:15 UTC, juanjosuem commented on src/components/practica1/Slider.js
> +		function Blog(props) {
misma observacion, esta funcion afuera de la clase, o en otro archivo

2018-06-11 18:11 UTC, antezananoemi commented
cambios solicitados

2018-06-11 18:12 UTC, merged